filters:
  departure: ""        # boş = kalkış filtresi yok
  arrivals: []         # boş dizi = varış filtresi yok
  max_price: 0         # 0 = sınırsız

message_template: |
  ✈️ {origin} → {destination} — {price} TL
  Tarihler: {dates}
  Kaynak: {url}
