name: Ucuz Uçak Tarayıcı

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      # (Opsiyonel) Önceki state'i indir
      - name: Download previous state artifact (optional)
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: ucuz-ucak.yml
          name: ucuz-ucak-state
          path: data
        continue-on-error: true

      - name: Run scraper (Playwright)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          mkdir -p data
          if [ ! -f data/state.json ]; then
            echo '{"seen_ids":{}}' > data/state.json
          fi
          python scraper.py

      - name: Upload state artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: ucuz-ucak-state
          path: data/state.json
          if-no-files-found: warn
